#! /usr/bin/env sh

while getopts d:f: option
do
case "${option}"
in
d) DELIMITER=${OPTARG};;
f) FILE=${OPTARG};;
esac
done

printf "d: %s\n" $DELIMITER
printf "f: %s\n" $FILE
$AWK = $(sprintf "BEGIN { FS=\"%s\" } { for(i = 1; i <= NF; i++) { printf(\"%d  %s\n\", i, \$i) } } " $DELIMITER)
head -n 1 $FILE | awk $AWK


