#! /usr/bin/env bash

SCRIPT_NAME=`basename "$0"`

usage() { echo "Usage: $SCRIPT_NAME [-d <\",\",\"|\",\"\\t\">] -f <filename>" 1>&2; exit 1; }

function column_list() {
  DELIMITER=$1
  FILE=$2
  head -n 1 $FILE | awk -v DELIMITER=$DELIMITER 'BEGIN { FS=DELIMITER } { for(i = 1; i <= NF; i++) { printf("%d  %s\n", i, $i) } } '
}

while getopts ":d:f:" ARGS; do
    case "${ARGS}" in
        d)
            d=${OPTARG}
            # ((d == "," || d == "\t")) || usage
            ;;
        f)
            f=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${f}" ]; then
    printf "-f parameter is required\n";
    usage;
    exit 1;
fi
if [ -z "${d}" ]; then
    # delimiter not given; use delim script to get delimiter
    d=`delim $f`;
fi
column_list "${d}" "${f}"
