#! /usr/bin/env bash

source delim;

SCRIPT_NAME=`basename "$0"`

usage() { echo "Usage: $SCRIPT_NAME <filename>" 1>&2; exit 1; }

function column_list() {
  DELIMITER=$1
  FILE=$2
  head -n 1 $FILE | awk -v DELIMITER=$DELIMITER 'BEGIN { FS=DELIMITER } { for(i = 1; i <= NF; i++) { printf("%d  %s\n", i, $i) } } '
}
if [ $# -eq 0 ]; then
    usage;
    exit 1;
fi
if [ ! -f $1 ]; then
    printf "'${1}' file does not exist\n";
    usage;
    exit 1;
else
    f="$1";
fi
# get delimiter
d=`delim $f`;
column_list "${d}" "${f}"
