#! /usr/bin/env bash

function lookup() {
  LOOKUP_COLUMN=$1
  LOOKUP_VALUE=$2
  OUTPUT_COLUMN=$3
  VERBOSE=0
  FILE=$5
  awk -v LOOKUP_COLUMN=$LOOKUP_COLUMN -v LOOKUP_VALUE=$LOOKUP_VALUE -v OUTPUT_COLUMN=$OUTPUT_COLUMN 'BEGIN { FS="|" } { for(i = 1; i <= NF; i++) if(i == LOOKUP_COLUMN && $i == LOOKUP_VALUE) { printf("%s\n", $OUTPUT_COLUMN) } } ' $FILE
  
  # if [ $VERBOSE -eq 1 ]
  # then
  #   printf "%s\n" $FILE
  #   awk -v LOOKUP_COLUMN=$LOOKUP_COLUMN -v LOOKUP_VALUE=$LOOKUP_VALUE -v OUTPUT_COLUMN=$OUTPUT_COLUMN 'BEGIN { FS="|" } { for(i = 1; i <= NF; i++) if(i == LOOKUP_COLUMN && $i == LOOKUP_VALUE) { printf("\tLINE %s: %s\n", FNR, $OUTPUT_COLUMN) } } ' $FILE
  # else
  # fi
}

if [ $# -eq 0 ]
then
  echo "usage: lookup LOOKUP_COLUMN LOOKUP_VALUE OUTPUT_COLUMN FILE";
elif [ $# -eq 4 ]
then
  LOOKUP_COLUMN=$1
  LOOKUP_VALUE=$2
  OUTPUT_COLUMN=$3
  FILE=$4
  VERBOSE=0
  lookup $LOOKUP_COLUMN $LOOKUP_VALUE $OUTPUT_COLUMN $VERBOSE $FILE 
elif [ $# -eq 3 ]
then
  printf "iterating over all files in:%s\n" $PWD
  LOOKUP_COLUMN=$1
  LOOKUP_VALUE=$2
  OUTPUT_COLUMN=$3
  VERBOSE=0
  find * -type f | while read FILE; do
    lookup $LOOKUP_COLUMN $LOOKUP_VALUE $OUTPUT_COLUMN $VERBOSE $FILE 
  done;
fi


