#! /usr/bin/env bash

function column_list() {
  FILE=$1
  DELIMITER=$2
  basename $FILE
  head -n 1 $FILE | awk -v DELIMITER=$DELIMITER 'BEGIN { FS=DELIMITER } { for(i = 1; i <= NF; i++) { printf("%d  %s\n", i, $i) } } '
}

if [ $# -eq 1 ];
then
  DELIMITER="|"
  FILE=$1
  column_list $FILE $DELIMITER
else [ $# -eq 2 ];
  FILE=$1
  DELIMITER=$2
  column_list $FILE $DELIMITER
fi