pip uninstall agate
pip uninstall agate-dbf
pip uninstall agate-excel
pip uninstall agate-sql
pip uninstall astroid
pip uninstall autopep8
pip uninstall Babel
pip uninstall backports.functools-lru-cache
pip uninstall configparser
pip uninstall csvkit
pip uninstall dbfread
pip uninstall enum34
pip uninstall et-xmlfile
pip uninstall future
pip uninstall isodate
pip uninstall isort
pip uninstall jdcal
pip uninstall lazy-object-proxy
pip uninstall leather
pip uninstall mccabe
pip uninstall openpyxl
pip uninstall parsedatetime
pip uninstall pip
pip uninstall pycodestyle
pip uninstall pylint
pip uninstall python-slugify
pip uninstall pytimeparse
pip uninstall pytz
pip uninstall setuptools
pip uninstall singledispatch
pip uninstall six
pip uninstall SQLAlchemy
pip uninstall Unidecode
pip uninstall wheel
pip uninstall wrapt
pip uninstall xlrd