USE DSDW
GO

DECLARE @schema_name varchar(max) = 'Community'
DECLARE @fq_table_name varchar(max) = DB_NAME()+'.?'
DECLARE @per_table_cmd varchar(max) = '''TRUNCATE TABLE '+@fq_table_name+''';'
DECLARE @sql_cmd varchar(max) = 'IF(OBJECT_SCHEMA_NAME(OBJECT_ID(''?''))) = '''+@schema_name+''' BEGIN '+'PRINT '+@per_table_cmd+' END';
EXEC sp_MSforeachtable @command1 = @sql_cmd


TRUNCATE TABLE DSDW.[Community].[CaseNoteContactFact]
TRUNCATE TABLE DSDW.[Community].[CaseNoteHeaderFact]
TRUNCATE TABLE DSDW.[Community].[MHVocationalEducationEmploymentFact]
TRUNCATE TABLE DSDW.[Community].[ClientGroupFact]
TRUNCATE TABLE DSDW.[Community].[MHVocationalPlacementFact]
TRUNCATE TABLE DSDW.[Community].[ClientRegisterFact]
TRUNCATE TABLE DSDW.[Community].[ImmunizationAlertFact]
TRUNCATE TABLE DSDW.[Community].[CriminalJusticeFact]
TRUNCATE TABLE DSDW.[Community].[MHVocationalSupportedEducationFact]
TRUNCATE TABLE DSDW.[Community].[ImmunizationHistoryFact]
TRUNCATE TABLE DSDW.[Community].[CurrentLocationFact]
TRUNCATE TABLE DSDW.[Community].[SchoolHistoryFact]
TRUNCATE TABLE DSDW.[Community].[DeathFact]
TRUNCATE TABLE DSDW.[Community].[DiagnosisFact]
TRUNCATE TABLE DSDW.[Community].[DiagnosisGAFFact]
TRUNCATE TABLE DSDW.[Community].[DischargeFact]
TRUNCATE TABLE DSDW.[Community].[EmploymentFact]
TRUNCATE TABLE DSDW.[Community].[GroupAttendanceFact]
TRUNCATE TABLE DSDW.[Community].[HoNOSAdultFact]
TRUNCATE TABLE DSDW.[Community].[HoNOSChildFact]
TRUNCATE TABLE DSDW.[Community].[ImmAdverseEventFact]
TRUNCATE TABLE DSDW.[Community].[DeletedParisHCCMRRActual]
TRUNCATE TABLE DSDW.[Community].[HoNOSLearningDisabilityFact]
TRUNCATE TABLE DSDW.[Community].[YouthClinicActivityFact]
TRUNCATE TABLE DSDW.[Community].[HouseHoldCompositionFact]
TRUNCATE TABLE DSDW.[Community].[IdentifierFact]
TRUNCATE TABLE DSDW.[Community].[InterventionFact]
TRUNCATE TABLE DSDW.[Community].[LegalStatusFact]
TRUNCATE TABLE DSDW.[Community].[MaritalStatusFact]
TRUNCATE TABLE DSDW.[Community].[IncomeFact]
TRUNCATE TABLE DSDW.[Community].[CareLevelFact]
TRUNCATE TABLE DSDW.[Community].[MDSHCCAboriginalFact]
TRUNCATE TABLE DSDW.[Community].[ServiceFact]
TRUNCATE TABLE DSDW.[Community].[ParentingFact]
TRUNCATE TABLE DSDW.[Community].[YouthClinicMedicalHistoryFact]
TRUNCATE TABLE DSDW.[Community].[DeletedParisHCCMRRService]
TRUNCATE TABLE DSDW.[Community].[ServiceVisitFact]
TRUNCATE TABLE DSDW.[Community].[DeletedParisHCCMRRClient]
TRUNCATE TABLE DSDW.[Community].[PersonFact]
TRUNCATE TABLE DSDW.[Community].[SLPActivityFact]
TRUNCATE TABLE DSDW.[Community].[PregnancyFact]
TRUNCATE TABLE DSDW.[Community].[YouthClinicTestResultFact]
TRUNCATE TABLE DSDW.[Community].[ReferralFact]
TRUNCATE TABLE DSDW.[Community].[WaitlistSuspensionFact]
TRUNCATE TABLE DSDW.[Community].[SchoolEducationFact]
TRUNCATE TABLE DSDW.[Community].[ReferralInPatientFact]
TRUNCATE TABLE DSDW.[Community].[SubstanceUseFact]
TRUNCATE TABLE DSDW.[Community].[PersonNameFact]
TRUNCATE TABLE DSDW.[Community].[WaitlistClientOfferFact]
TRUNCATE TABLE DSDW.[Community].[InvolvedProfessionFact]
TRUNCATE TABLE DSDW.[Community].[WaitlistDefinitionFact]
TRUNCATE TABLE DSDW.[Community].[InvoiceHeaderFact]
TRUNCATE TABLE DSDW.[Community].[WaitlistEntryFact]
TRUNCATE TABLE DSDW.[Community].[InvoiceClientVisitFact]
TRUNCATE TABLE DSDW.[Community].[WaitlistProviderOfferFact]
TRUNCATE TABLE DSDW.[Community].[InvoiceClientFact]
TRUNCATE TABLE DSDW.[Community].[WeightGrowthFact]
TRUNCATE TABLE DSDW.[Community].[FundingSourceFact]
TRUNCATE TABLE DSDW.[Community].[FinancialAssessmentFact]
TRUNCATE TABLE DSDW.[Community].[ScreeningResultFact]
TRUNCATE TABLE DSDW.[Community].[CarePlanHeaderFact]
TRUNCATE TABLE DSDW.[Community].[CarePlanPatternFact]
TRUNCATE TABLE DSDW.[Community].[MedRecFact]
TRUNCATE TABLE DSDW.[Community].[CarePlanNeedFact]
TRUNCATE TABLE DSDW.[Community].[ClientGPFact]
TRUNCATE TABLE DSDW.[Community].[HSServiceSummaryFact]
TRUNCATE TABLE DSDW.[Community].[AssessmentContactFact]
TRUNCATE TABLE DSDW.[Community].[CDExposureFact]
TRUNCATE TABLE DSDW.[Community].[RiskScreenerFact]
TRUNCATE TABLE DSDW.[Community].[CDTestResultFact]
TRUNCATE TABLE DSDW.[Community].[CDLabReportFact]
TRUNCATE TABLE DSDW.[Community].[DeletedParisHCCMRRIncome]
TRUNCATE TABLE DSDW.[Community].[CDPreviousTestResultFact]
TRUNCATE TABLE DSDW.[Community].[CDPublicHealthMeasureFact]
TRUNCATE TABLE DSDW.[Community].[ClientFact]
TRUNCATE TABLE DSDW.[Community].[PatientFocusFundingFact]
TRUNCATE TABLE DSDW.[Community].[ProviderBedHistoryFact]
TRUNCATE TABLE DSDW.[Community].[MedicationFact]
TRUNCATE TABLE DSDW.[Community].[AbuseFact]
TRUNCATE TABLE DSDW.[Community].[CDRabiesFact]
TRUNCATE TABLE DSDW.[Community].[AddressFact]
TRUNCATE TABLE DSDW.[Community].[AlertFact]
TRUNCATE TABLE DSDW.[Community].[AssessmentHeaderFact]
TRUNCATE TABLE DSDW.[Community].[CaseNoteClinicalServiceFact]
TRUNCATE TABLE DSDW.[Community].[MHVocationalAssessmentFact]
